### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by Banou26** [MightyAlex200/tfjs-tts#1]
Hey,

I'm super interested in what you've done with this repo, I also tried playing around with TensorflowTTS but when it came to converting the TS SavedModel with tensorflowjs_wizard i encountered some problems.
Would you mind documenting how you managed to convert the model or maybe would you have any tips on problems to look for? I'd really appreciate it!
It's totally fine if you don't want to share how you managed to do it too, I'll just try harder.

Thanks for your time.

**Comment by MightyAlex200** [comment]
Hey there! It's cool to have someone interested in my project like this. :)
I couldn't get TensorflowTTS working directly on my machine, so I used Google Colab to export the models. I used [this][colab] notebook, executing the cells to create `fastspeech2` and `mb_melgan`. I then exported them with this code:
**Note: at this point, you should have run the model at least once.**
```python
fastspeech2.save('text2mel', signatures=fastspeech2.inference)
mb_melgan.save('vocoder', signatures=mb_melgan.inference)
```
After that, I zipped the two directories up and downloaded them to my machine:
```
!zip -r text2mel.zip text2mel
!zip -r vocoder.zip vocoder
```
I then used `tensorflowjs_wizard` to convert the file. I extracted the folder and set it as the input for the wizard. I used the default settings except for "model format"; I changed this to "Tensorflow Saved Model." Unfortunately, after that, we have to deal with a bit of jank from Tensorflow's side. The TensorflowJS converter picks arbitrary indices for its outputs. The array access you may need to change is current at [line 318 in `index.js`][index]. After that, the conversion should be complete!

I hope this was helpful to you. I am happy to answer any more questions you may have!

_I am also working on a native version of FastSpeech2 for TensorflowJS. It will likely have significantly improved performance. I will release it on my GitHub page when it is finished, so you may follow me if you want to hear when it is done._

[colab]: https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD
[index]: https://github.com/MightyAlex200/tfjs-tts/blob/eb80e94ab75e32e84c823a4611e494b0c1e29d51/index.js#L318
